### ISSUE TITLE
Could you add this feature right now............PLEASE ???

### ISSUE THREAD

**Issue by mlaprise** [msukmanowsky/django-naics-scian#1]
Hi, wondering if you could a ${FEATURE} for my ${REALLY UNIQUE AND SPECIFIC USE CASE}

thx !

**Comment by msukmanowsky** [comment]
lol how the hell did you find this repo so fast!? #wontfix

**Comment by mlaprise** [comment]
LOL, I saw your repo pop up in my GitHub feed... looks like I following you on GitHub. Happy coding !
